spring:
  port: 18080
  application:
    name: learning-tx
  active:
    profiles: dev

# ???? ??? DB
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  logging:
    level:
      root: INFO
      org.springframework.transaction: DEBUG
#      org.hibernate.SQL: DEBUG
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE